"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CartesianGrid, PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import { quoteCsv } from "../lib/csv";
import { EvidenceSummary, LensManager, ObservationEditor, PlayerPreview, ReviewInbox, ScatterDiscovery } from "./ScoutingTools";
import type { AnalysisLens } from "../lib/lenses";
import { CandidateCards, SearchPresets } from "./WorkflowViews";
import { BriefDecisionCompare, DatasetAudit, Dossier, EvidencePanel, NearMisses, ProjectReview } from "./DecisionTools";
import { assessBrief, buildPercentiles, identity, initialBrief, labels, observed, percentile, rankingDiagnostics, resemblance, profileSignature, safeEvidenceUrl, validateProject, weights } from "../lib/recruitment";
import type { BriefRule, ProjectEntry, RecruitmentBrief, RecruitmentProject, ScoutPlayer } from "../lib/recruitment";

type Props = { players: ScoutPlayer[]; pool: ScoutPlayer[]; target: ScoutPlayer; features: string[]; datasetVersion: string; generatedAt?: string; dataMode?: string; priorities: Record<string, number>; quickShortlist: ScoutPlayer[]; onScout: (p: ScoutPlayer) => void };
const colors = ["#ff2d8d", "#83e63f", "#27d8ff", "#ffcc3d"];
const storageKey = "scoutlab-recruitment-projects-v1";
const tabs = ["Brief", "Candidates", "Brief compare", "Report", "Compare", "Projects", "Checks"] as const;
const blankEntry = (key: string): ProjectEntry => ({ key, status: "Longlist", strengths: "", concerns: "", note: "", evidenceUrl: "" });
function download(name: string, content: string, type = "application/json") {
  const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function valueText(value: number | null, unit: BriefRule["unit"] = "percentile") { return value === null ? "Unavailable" : unit === "percentile" ? `${value.toFixed(1)} percentile` : `${value.toFixed(2)} /90`; }
function PercentBar({ value, color = "#b8ff3d" }: { value: number | null; color?: string }) { return <div className="desk-bar"><i style={{ width: `${value ?? 0}%`, background: color }} /></div>; }

export default function RecruitmentDesk(props: Props) {
  const { players, pool, target, features, datasetVersion, generatedAt, dataMode, priorities, quickShortlist, onScout } = props;
  const [tab, setTab] = useState<typeof tabs[number]>("Brief");
  const [brief, setBrief] = useState<RecruitmentBrief>(() => initialBrief(target.position, target.season ?? "", features));
  const [projects, setProjects] = useState<RecruitmentProject[]>([]);
  const [activeId, setActiveId] = useState("");
  const [storageReady, setStorageReady] = useState(false);
  const [notice, setNotice] = useState("");
  const [projectName, setProjectName] = useState("");
  const [reportKey, setReportKey] = useState("");
  const [showFailures, setShowFailures] = useState(false);
  const [sort, setSort] = useState("brief");
  const [comparisonKeys, setComparisonKeys] = useState<string[]>([]);
  const [briefComparisonKeys, setBriefComparisonKeys] = useState<string[]>([]);
  const [dossierPlayers, setDossierPlayers] = useState<ScoutPlayer[] | null>(null);
  const [addKey, setAddKey] = useState("");
  const [reference, setReference] = useState(true);
  const [chartFeature, setChartFeature] = useState(features[0]);
  const [xFeature, setXFeature] = useState(features.includes("xg_p90") ? "xg_p90" : features[0]);
  const [yFeature, setYFeature] = useState(features.includes("goals_p90") ? "goals_p90" : features[1] ?? features[0]);
  const [view, setView] = useState<"percentile" | "per90">("percentile");
  const [lensMetrics,setLensMetrics]=useState<string[]>(features);
  const [lensPriorities,setLensPriorities]=useState<Record<string,number>|null>(null);
  const [preview,setPreview]=useState<{key:string;context:"brief"|"charts"}|null>(null);
  const [expandedEntry,setExpandedEntry]=useState("");
  const closePreview=useCallback(()=>setPreview(null),[]);
  const displayFeatures=features.filter(f=>lensMetrics.includes(f));
  const metricWeights = useMemo(() => weights(target.position, lensPriorities??priorities), [target.position, priorities,lensPriorities]);
  const lookup = useMemo(() => buildPercentiles(pool, features), [pool, features]);
  const briefPool = useMemo(() => players.filter(p => p.position === brief.position && p.season === brief.season), [players, brief.position, brief.season]);
  const briefLookup = useMemo(() => buildPercentiles(briefPool, features), [briefPool, features]);
  const activeProject = projects.find(p => p.id === activeId);
  const dossierLookup = useMemo(() => {
    const output = {};
    const cohorts = new Set((dossierPlayers ?? []).map(p => JSON.stringify([p.position,p.season])));
    cohorts.forEach(key => { const [position,season] = JSON.parse(key); Object.assign(output,buildPercentiles(players.filter(p => p.position===position && p.season===season),features)); });
    return output;
  }, [dossierPlayers,players,features]);

  useEffect(() => {
    try {
      const saved = window.localStorage.getItem(storageKey);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (!Array.isArray(parsed) || parsed.length > 20) throw new Error("Invalid saved projects");
        const restored = parsed.map(p => validateProject({ schemaVersion: 1, project: p }));
        setProjects(restored); if (restored[0]) { setActiveId(restored[0].id); setBrief(restored[0].brief); }
      }
      setStorageReady(true);
    } catch { setNotice("Saved projects could not be read. Existing browser storage was left untouched. You can still export this session's work."); }
  }, []);
  useEffect(() => {
    if (!storageReady) return;
    try {
      projects.forEach(p=>validateProject({schemaVersion:1,project:p}));
      window.localStorage.setItem(storageKey, JSON.stringify(projects));
    } catch { setNotice("Project changes could not be saved. Check blank brief names or invalid evidence links, and export valid work before leaving."); }
  }, [projects, storageReady]);
  useEffect(() => { setComparisonKeys([]); setAddKey(""); setReportKey(""); }, [target.player_name, target.season, target.position, target.club]);
  useEffect(() => { setBriefComparisonKeys([]); }, [brief.position,brief.season]);
  useEffect(() => { setLensPriorities(null); setLensMetrics(features); }, [target.position,features]);

  function editBrief(next: RecruitmentBrief) {
    setBrief(next);
    if (activeId) setProjects(current => current.map(p => p.id === activeId ? { ...p, brief: next } : p));
  }
  function entryFor(p:ScoutPlayer):ProjectEntry {return {...blankEntry(identity(p)),profileSignature:profileSignature(p,features),reviewedDatasetVersion:datasetVersion};}
  function applyLens(lens:AnalysisLens){setLensMetrics(lens.metrics);setXFeature(lens.x);setYFeature(lens.y);setChartFeature(lens.distribution);setView(lens.basis);setReference(lens.reference);setLensPriorities(lens.priorities);setNotice(`Applied ${lens.name}. Search requirements are unchanged; similarity priorities are now from this lens.`);}
  function toggleChartPlayer(p:ScoutPlayer){const key=identity(p);if(key===identity(target)){setNotice("The reference player stays in profile comparisons.");return;}if(!comparisonKeys.includes(key)&&comparisonKeys.length>=3){setNotice("Compare up to four players. Remove one before adding another.");return;}setComparisonKeys(current=>current.includes(key)?current.filter(k=>k!==key):[...current,key]);}
  function toggleBriefPlayer(p:ScoutPlayer){const key=identity(p);if(!briefComparisonKeys.includes(key)&&briefComparisonKeys.length>=4){setNotice("Compare up to four candidates. Remove one before adding another.");return;}setBriefComparisonKeys(current=>current.includes(key)?current.filter(k=>k!==key):[...current,key]);}
  function createProject(entries: ProjectEntry[] = []) {
    if (projects.length >= 20) { setNotice("This browser supports up to 20 projects. Export a project before removing it."); return; }
    const name = projectName.trim() || brief.name.trim() || "Recruitment brief";
    const p: RecruitmentProject = { id: crypto.randomUUID(), name, brief: { ...brief, name }, entries, datasetVersion, createdAt: new Date().toISOString() };
    setProjects(current => [...current, p]); setActiveId(p.id); setBrief(p.brief); setProjectName(""); setNotice(`Created ${name}. Notes and brief changes save in this browser.`);
    return p.id;
  }
  function addCandidate(p: ScoutPlayer) {
    if (!activeProject) { createProject([entryFor(p)]); return; }
    if (activeProject.entries.some(e => e.key === identity(p))) { setNotice("That player is already in this project."); return; }
    if (activeProject.entries.length >= 64) { setNotice("A project can hold up to 64 candidates."); return; }
    setProjects(current => current.map(project => project.id === activeId ? { ...project, entries: [...project.entries, entryFor(p)] } : project));
    setNotice(`Added ${p.player_name} to ${activeProject.name}.`);
  }
  function updateEntry(key: string, update: Partial<ProjectEntry>) { setProjects(current => current.map(p => p.id === activeId ? { ...p, entries: p.entries.map(e => e.key === key ? { ...e, ...update } : e) } : p)); }
  function switchProject(id: string) { setActiveId(id); const p = projects.find(p => p.id === id); if (p) setBrief(p.brief); setNotice(""); }
  const candidates = useMemo(() => briefPool.filter(p => identity(p) !== identity(target)).map(p => ({ player: p, assessment: assessBrief(p, brief, briefLookup), similarity: resemblance(target, p, features, lookup, metricWeights) })).filter(p => showFailures || p.assessment.eligible).sort((a,b) => (sort === "similarity" ? (b.similarity ?? -1)-(a.similarity ?? -1) : (b.assessment.score ?? -1)-(a.assessment.score ?? -1)) || (b.similarity ?? -1)-(a.similarity ?? -1) || identity(a.player).localeCompare(identity(b.player))), [briefPool, target, brief, briefLookup, features, lookup, metricWeights, showFailures, sort]);
  const reportPlayer = players.find(p => identity(p) === reportKey) ?? target;
  const reportCohort = useMemo(() => players.filter(p => p.position === reportPlayer.position && p.season === reportPlayer.season), [players, reportPlayer.position, reportPlayer.season]);
  const reportLookup = useMemo(() => buildPercentiles(reportCohort, features), [reportCohort, features]);
  const reportAssessment = assessBrief(reportPlayer, brief, reportLookup);
  const signals = features.map(f => ({ feature: f, value: percentile(reportPlayer, f, reportLookup), raw: observed(reportPlayer, f) })).filter(s => s.value !== null).sort((a,b) => b.value!-a.value!);
  const reportSimilarity = resemblance(target, reportPlayer, features, lookup, metricWeights);
  const differences = features.map(f=>({feature:f,a:percentile(target,f,lookup),b:percentile(reportPlayer,f,lookup)})).filter(s=>s.a!==null&&s.b!==null).sort((a,b)=>Math.abs(b.b!-b.a!)-Math.abs(a.b!-a.a!)).slice(0,3);
  const comparePlayers = [target, ...comparisonKeys.map(key => pool.find(p => identity(p) === key)).filter((p): p is ScoutPlayer => Boolean(p))].slice(0,4);
  const radarData = displayFeatures.map(f => {
    const available = pool.map(p => percentile(p,f,lookup)).filter((v): v is number => v !== null);
    return { metric: labels[f] ?? f, ...Object.fromEntries(comparePlayers.map((p,i) => [`p${i}`,percentile(p,f,lookup)])), average: available.length ? available.reduce((sum,value)=>sum+value,0)/available.length : null };
  });
  const distributionValues = pool.map(p=>observed(p,chartFeature)).filter((v):v is number=>v!==null);
  const histogramMax = Math.max(...distributionValues, .01);
  const bins = Array.from({length:10},(_,i)=>({start:i*histogramMax/10,end:(i+1)*histogramMax/10,count:distributionValues.filter(v=>Math.min(9,Math.floor(v/histogramMax*10))===i).length}));
  const diagnostics = useMemo(() => tab === "Checks" ? rankingDiagnostics(pool,target,features,metricWeights) : null, [tab,pool,target,features,metricWeights]);

  const previewPlayer=players.find(p=>identity(p)===preview?.key);
  const previewPool=useMemo(()=>previewPlayer?players.filter(p=>p.position===previewPlayer.position&&p.season===previewPlayer.season):[],[players,previewPlayer]);
  const previewLookup=useMemo(()=>buildPercentiles(previewPool,features),[previewPool,features]);
  const savedKeys=[...new Set([...quickShortlist.map(identity),...projects.flatMap(p=>p.entries.map(e=>e.key))])];
  useEffect(()=>{if(tab!=="Projects"||!expandedEntry)return;const frame=requestAnimationFrame(()=>document.getElementById(`review-${encodeURIComponent(expandedEntry)}`)?.scrollIntoView({block:"center",behavior:"smooth"}));return()=>cancelAnimationFrame(frame);},[tab,expandedEntry,activeId]);

  function exportReport() {
    const text = [`SCOUT//LAB — ${reportPlayer.player_name}`,`${reportPlayer.club} · ${reportPlayer.position} · ${reportPlayer.season} · ${reportPlayer.minutes ?? 0} minutes`,`Dataset: ${datasetVersion} · exported ${generatedAt ?? "date not supplied"}`,`Cohort: ${reportCohort.length} profiles; 900-minute ranking prior`,`Brief: ${brief.name} · ${reportAssessment.eligible ? "Mandatory requirements met" : "Mandatory requirements not met"}`,`Brief attainment: ${reportAssessment.score?.toFixed(1) ?? "not scored"}; resemblance to ${target.player_name}: ${reportSimilarity?.toFixed(1) ?? "unavailable"}`,"",...signals.map(s=>`${labels[s.feature]}: ${s.raw?.toFixed(2) ?? "unavailable"} /90, ${s.value!.toFixed(1)} percentile`),"",...reportAssessment.checks.map(c=>`${labels[c.feature]}: ${valueText(c.value,c.unit)}; minimum ${c.minimum}; ${c.required?"mandatory":"preference"}; ${c.met?"met":"not met"}`),"","Limits: attacking-profile evidence only; no transfer-success prediction, comprehensive defensive assessment or inferred touch locations."];
    download(`scoutlab-report-${reportPlayer.player_id}.txt`,text.join("\n"),"text/plain;charset=utf-8");
  }
  function exportComparison() {
    const esc = (s:string)=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
    const h=160+features.length*100;
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${h}" viewBox="0 0 1200 ${h}"><rect width="1200" height="${h}" fill="#07100f"/><text x="30" y="38" fill="#b8ff3d" font-size="22" font-family="sans-serif">SCOUT//LAB · ${esc(String(target.season))} · ${esc(target.position)} · Percentiles</text><text x="30" y="65" fill="#83928f" font-size="14" font-family="sans-serif">${esc(datasetVersion)} · ${pool.length} cohort profiles · 900-minute prior · Not a player-quality rating</text>${comparePlayers.map((p,i)=>`<text x="${30+i*290}" y="102" fill="${colors[i]}" font-size="17" font-family="sans-serif">${esc(p.player_name)}</text>`).join("")}${features.map((f,j)=>`<text x="30" y="${150+j*100}" fill="#f3f7f5" font-size="16" font-family="sans-serif">${esc(labels[f])}</text>${comparePlayers.map((p,i)=>{const v=percentile(p,f,lookup);return `<rect x="220" y="${132+j*100+i*17}" width="${(v??0)*8}" height="10" rx="3" fill="${colors[i]}"/><text x="1050" y="${142+j*100+i*17}" fill="${colors[i]}" font-size="13" font-family="sans-serif">${v?.toFixed(1)??"N/A"}</text>`;}).join("")}`).join("")}</svg>`;
    download("scoutlab-comparison.svg",svg,"image/svg+xml");
  }
  async function importProject(file: File | undefined) {
    if (!file) return;
    try {
      if (file.size > 2*1024*1024) throw new Error("Project files must be smaller than 2 MB.");
      if (projects.length >= 20) throw new Error("Export and remove a project before adding another.");
      const imported = validateProject(JSON.parse(await file.text()));
      if (imported.brief.rules.some(r=>!features.includes(r.feature))) throw new Error("This project requires metrics not available in this dataset.");
      const next = { ...imported, id: crypto.randomUUID() };
      setProjects(current=>[...current,next]);setActiveId(next.id);setBrief(next.brief);setNotice("Project imported as a separate copy. Missing dataset profiles remain listed, not discarded.");
    } catch(error) { setNotice(error instanceof Error ? error.message : "Project import failed."); }
  }

  return <section id="recruitment-desk" className="desk panel">
    <div className="desk-heading"><div><span className="eyebrow">Recruitment workspace</span><h2>Find your fit.</h2><p>Start with what you need. Explore your options. Keep the players worth a closer look.</p></div><button className="flow-tools" aria-pressed={tab==="Checks"} onClick={()=>setTab(tab==="Checks"?"Candidates":"Checks")}>{tab==="Checks"?"← Back to candidates":"Analysis tools ↗"}</button></div>
    <nav className="flow-steps" aria-label="Recruitment workflow">{([{key:"Brief",name:"Define your search",detail:"Choose what matters"},{key:"Candidates",name:"Review candidates",detail:"Explore & compare"},{key:"Projects",name:"Your shortlist",detail:`${activeProject?.entries.length??0} saved in this project`}] as const).map((step,i)=>{const active=step.key==="Brief"?tab==="Brief":step.key==="Projects"?tab==="Projects":["Candidates","Report","Brief compare","Compare"].includes(tab);return <button key={step.key} aria-current={active?"step":undefined} onClick={()=>setTab(step.key)}><b>0{i+1}</b><span><strong>{step.name}</strong><small>{step.detail}</small></span><i aria-hidden="true">→</i></button>;})}</nav>
    {previewPlayer&&<PlayerPreview player={previewPlayer} features={features} lookup={previewLookup} brief={brief} cohortSize={previewPool.length} generatedAt={generatedAt} saved={activeProject?.entries.some(e=>e.key===identity(previewPlayer))??false} selected={preview?.context==="charts"?comparePlayers.some(p=>identity(p)===identity(previewPlayer)):briefComparisonKeys.includes(identity(previewPlayer))} comparisonCount={preview?.context==="charts"?comparePlayers.length:briefComparisonKeys.length} comparisonLimit={4} onClose={closePreview} onSave={()=>addCandidate(previewPlayer)} onCompare={preview?.context==="charts"&&identity(previewPlayer)===identity(target)?undefined:()=>preview?.context==="charts"?toggleChartPlayer(previewPlayer):toggleBriefPlayer(previewPlayer)} onReport={()=>{setReportKey(identity(previewPlayer));closePreview();setTab("Report");}}/>}
    {notice && <p className="desk-notice" role="status">{notice}</p>}
    {["Candidates","Report","Brief compare","Compare"].includes(tab)&&<div className="flow-review-nav"><div><span className="eyebrow">{brief.position} · {brief.season}</span><p>{brief.name} · {brief.minimumMinutes}+ minutes</p></div><div><button aria-pressed={tab==="Candidates"} onClick={()=>setTab("Candidates")}>{tab==="Candidates"?"Candidates":"← Candidates"}</button><button disabled={briefComparisonKeys.length<2} aria-pressed={tab==="Brief compare"} onClick={()=>setTab("Brief compare")}>Compare selected ({briefComparisonKeys.length}/4)</button><button aria-pressed={tab==="Compare"} onClick={()=>setTab("Compare")}>Profile charts</button></div></div>}
    <div role="region" id={`desk-view-${tab}`} aria-label={tab==="Brief"?"Define your search":tab==="Projects"?"Your shortlist":tab==="Checks"?"Analysis tools":tab==="Candidates"?"Review candidates":tab}>
    {tab === "Brief compare" && <BriefDecisionCompare pool={briefPool} brief={brief} lookup={briefLookup} selected={briefComparisonKeys} onSelected={setBriefComparisonKeys} features={features} generatedAt={generatedAt} onReport={p=>{setReportKey(identity(p));setTab("Report");}} onDossier={setDossierPlayers}/>}
    {tab === "Brief" && <>
      <div className="flow-intro"><h3>What should this player bring?</h3><p>Pick a starting point below. You can tune the targets whenever you need.</p></div>
      <SearchPresets brief={brief} features={features} onChange={editBrief}/>
      {brief.position==="Defender"&&<p className="desk-warning">These searches describe attacking contributions, not defensive ability.</p>}
      <div className="desk-form-grid"><label>Brief name<input maxLength={120} value={brief.name} onChange={e=>editBrief({...brief,name:e.target.value})}/></label><label>Position<select value={brief.position} onChange={e=>editBrief({...brief,position:e.target.value})}>{[...new Set(players.map(p=>p.position))].map(p=><option key={p}>{p}</option>)}</select></label><label>Season<select value={brief.season} onChange={e=>editBrief({...brief,season:e.target.value})}>{[...new Set(players.map(p=>p.season).filter(Boolean))].sort().map(s=><option key={s}>{s}</option>)}</select></label><label>Minimum minutes<input type="number" min={0} max={10000} value={brief.minimumMinutes} onChange={e=>editBrief({...brief,minimumMinutes:Math.min(10000,Math.max(0,Number(e.target.value)))})}/></label></div>
      <div className="flow-target-summary"><span>Your search targets</span>{brief.rules.map(r=><span key={r.feature}>{labels[r.feature]} <b>{r.required?"Required":"Preferred"}</b></span>)}</div>
      <details className="flow-advanced"><summary>Fine-tune targets <span>Optional · thresholds, weights & sorting</span></summary>
      <div className="desk-toolbar"><p>Mandatory requirements determine eligibility. Weights determine threshold attainment—not overall quality.</p><button onClick={()=>editBrief({...brief,position:target.position,season:target.season??""})}>Use selected cohort</button></div>
      <div className="desk-rule-list">{brief.rules.map((r,i)=><div className="desk-rule" key={r.feature}><label>Metric<select aria-label={`Requirement ${i+1} metric`} value={r.feature} onChange={e=>editBrief({...brief,rules:brief.rules.map((rule,index)=>index===i?{...rule,feature:e.target.value}:rule)})}>{features.filter(f=>f===r.feature||!brief.rules.some(rule=>rule.feature===f)).map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><label>Basis<select aria-label={`Requirement ${i+1} basis`} value={r.unit} onChange={e=>editBrief({...brief,rules:brief.rules.map((rule,index)=>index===i?{...rule,unit:e.target.value as BriefRule["unit"],minimum:e.target.value==="per90"?.2:60}:rule)})}><option value="percentile">Percentile</option><option value="per90">Recorded /90</option></select></label><label>Minimum<input aria-label={`Requirement ${i+1} minimum`} type="number" min={0} max={r.unit==="percentile"?100:1000} step={r.unit==="percentile"?1:.05} value={r.minimum} onChange={e=>editBrief({...brief,rules:brief.rules.map((rule,index)=>index===i?{...rule,minimum:Math.max(0,Math.min(r.unit==="percentile"?100:1000,Number(e.target.value)))}:rule)})}/></label><label>Weight<input aria-label={`Requirement ${i+1} weight`} type="number" min={0} max={100} value={r.weight} onChange={e=>editBrief({...brief,rules:brief.rules.map((rule,index)=>index===i?{...rule,weight:Math.max(0,Math.min(100,Number(e.target.value)))}:rule)})}/></label><label className="desk-check"><input type="checkbox" aria-label={`Requirement ${i+1} mandatory`} checked={r.required} onChange={e=>editBrief({...brief,rules:brief.rules.map((rule,index)=>index===i?{...rule,required:e.target.checked}:rule)})}/>Mandatory</label><button aria-label={`Remove ${labels[r.feature]} requirement`} onClick={()=>editBrief({...brief,rules:brief.rules.filter((_,index)=>index!==i)})}>×</button></div>)}</div>
      <div className="desk-toolbar"><button disabled={brief.rules.length>=features.length} onClick={()=>{const feature=features.find(f=>!brief.rules.some(r=>r.feature===f));if(feature)editBrief({...brief,rules:[...brief.rules,{feature,minimum:60,unit:"percentile",required:false,weight:25}]});}}>+ Add metric</button><button onClick={()=>{createProject();setTab("Projects");}}>Save as new project</button><label className="desk-check"><input type="checkbox" checked={showFailures} onChange={e=>setShowFailures(e.target.checked)}/>Include unmet requirements</label><label>Rank by<select aria-label="Brief ranking" value={sort} onChange={e=>setSort(e.target.value)}><option value="brief">Brief attainment</option><option value="similarity">Profile similarity</option></select></label></div>
      </details>
      <div className="flow-next"><div><strong>{candidates.filter(c=>c.assessment.eligible).length} players meet your required targets</strong><p>From {briefPool.length} profiles in this position and season. Presets are editable search filters—not tactical ratings.</p></div><button className="flow-primary" onClick={()=>setTab("Candidates")}>Review candidates →</button></div>
    </>}
    {tab === "Candidates" && <>
      <div className="flow-intro"><h3>Who deserves a closer look?</h3><p>Compare up to four players, or save someone to your shortlist. Start with the fit, then open the numbers if you need them.</p></div>
      <div className="flow-filter-row"><label className="desk-check"><input type="checkbox" checked={showFailures} onChange={e=>setShowFailures(e.target.checked)}/>Show players who miss a required target</label><label>Order by<select aria-label="Candidate order" value={sort} onChange={e=>setSort(e.target.value)}><option value="brief">Search targets met</option><option value="similarity">Similarity to {target.player_name}</option></select></label></div>
      <CandidateCards key={brief.position+"-"+brief.season} candidates={candidates} brief={brief} lookup={briefLookup} features={features} generatedAt={generatedAt} selected={briefComparisonKeys} saved={activeProject?.entries.map(e=>e.key)??[]} onSelected={setBriefComparisonKeys} onSave={addCandidate} onReport={p=>setPreview({key:identity(p),context:"brief"})}/>
      <details className="flow-advanced"><summary>Players just outside your search <span>Explore explained near-misses</span></summary><NearMisses pool={briefPool} target={target} brief={brief} lookup={briefLookup} features={features} generatedAt={generatedAt} onReport={p=>{setReportKey(identity(p));setTab("Report");}} onAdd={addCandidate}/></details>
      <div className="flow-next"><p>Your shortlist keeps notes, next actions and reports together.</p><button onClick={()=>setTab("Projects")}>View your shortlist →</button></div>
    </>}
    {tab === "Report" && <>
      <div className="desk-toolbar"><button onClick={()=>setDossierPlayers([reportPlayer])}>Preview player dossier</button><span>Includes the brief, measured profile, trade-offs and active project notes.</span></div>
      <details className="flow-advanced"><summary>Sample & source details <span>Coverage, minutes & freshness</span></summary><EvidencePanel player={reportPlayer} features={features} generatedAt={generatedAt}/></details>
      <div className="desk-toolbar"><label>Player report<select aria-label="Report player" value={identity(reportPlayer)} onChange={e=>setReportKey(e.target.value)}>{[target,...pool.filter(p=>identity(p)!==identity(target))].map(p=><option key={identity(p)} value={identity(p)}>{p.player_name}</option>)}{!pool.some(p=>identity(p)===identity(reportPlayer))&&<option value={identity(reportPlayer)}>{reportPlayer.player_name}</option>}</select></label><button onClick={exportReport}>Download report</button><button onClick={()=>addCandidate(reportPlayer)}>+ Add to project</button><button onClick={()=>onScout(reportPlayer)}>Open profile</button></div>
      <div className="desk-report-head"><span className="eyebrow">Evidence-backed player report</span><h3>{reportPlayer.player_name}</h3><p>{reportPlayer.club} · {reportPlayer.position} · {reportPlayer.season} · {reportPlayer.minutes?.toLocaleString()} minutes</p><div className="desk-report-facts"><span>{reportCohort.length} cohort profiles</span><span>{Number(reportPlayer.minutes??0)<900?"Early sample":Number(reportPlayer.minutes??0)<1800?"Building sample":"Established sample"}</span><span>{dataMode==="demo"?"Fictional demonstration":"Imported snapshot"}</span></div></div>
      <EvidenceSummary player={reportPlayer} features={features} lookup={reportLookup} brief={brief} cohortSize={reportCohort.length} generatedAt={generatedAt}/>
      <div className="desk-report-grid"><article><h4>Strongest measured signals</h4>{signals.slice(0,3).map(s=><div className="desk-signal" key={s.feature}><span>{labels[s.feature]}</span><strong>{s.value!.toFixed(1)} percentile</strong><PercentBar value={s.value}/><small>{s.raw?.toFixed(2)} /90 · measured attacking output, not an inferred tactical skill</small></div>)}</article><article><h4>Lower-ranked measured signals</h4>{signals.slice(-3).reverse().map(s=><div className="desk-signal" key={s.feature}><span>{labels[s.feature]}</span><strong>{s.value!.toFixed(1)} percentile</strong><PercentBar value={s.value} color="#ffcc3d"/><small>{s.raw?.toFixed(2)} /90 · lower relative rank does not establish a weakness in every role</small></div>)}</article><article><h4>Does this meet your brief?</h4><p>{brief.name}</p><strong className={reportAssessment.eligible?"desk-pass":"desk-warning"}>{reportAssessment.eligible?"Mandatory requirements met":"Mandatory requirements not met"}</strong><ul>{reportAssessment.gates.map(g=><li key={g}>{g}</li>)}{reportAssessment.checks.map(c=><li key={c.feature}>{labels[c.feature]}: {valueText(c.value,c.unit)}; minimum {c.minimum} · {c.met?"met":"not met"}{c.required?" (mandatory)":""}</li>)}</ul><p>Weighted threshold attainment: {reportAssessment.score?.toFixed(1)??"not scored"}/100.</p></article><article><h4>Difference from {target.player_name}</h4><p>{identity(target)===identity(reportPlayer)?"This is the selected reference player.":reportSimilarity===null?"Different cohort or incomplete data: resemblance is not scored.":`${reportSimilarity.toFixed(1)}% statistical resemblance under your current priorities.`}</p>{reportSimilarity!==null&&identity(target)!==identity(reportPlayer)&&<ul>{differences.map(d=><li key={d.feature}>{labels[d.feature]}: {((d.b??0)-(d.a??0))>=0?"+":""}{((d.b??0)-(d.a??0)).toFixed(1)} percentile points ({d.b!.toFixed(1)} vs {d.a!.toFixed(1)}).</li>)}</ul>}</article></div>
      <div className="desk-evidence-note"><strong>Before making a decision</strong><ul><li>Review video for positioning, pressing, off-ball work and tactical responsibilities; these are not established by the available metrics.</li><li>Check role, opposition and team context before treating per-90 output as transferable.</li><li>Confirm the season and source freshness. Export timestamp: {generatedAt?.slice(0,10)??"not supplied"}; dataset: {datasetVersion}. An export date is not the latest match date.</li></ul><p>No external AI service is used. Every automated statement comes from the displayed metrics, sample size or requirements. Missing metrics: {features.filter(f=>observed(reportPlayer,f)===null).map(f=>labels[f]).join(", ")||"none among the supplied features"}. Defensive, physical and touch-location coverage is not inferred.</p></div>
    </>}
    {tab === "Compare" && <>
      <LensManager key={target.position} position={target.position} features={features} current={{position:target.position,metrics:displayFeatures,x:xFeature,y:yFeature,distribution:chartFeature,basis:view,reference,priorities:lensPriorities??priorities}} onApply={applyLens} onNotice={setNotice}/>
      <details className="flow-advanced"><summary>Customize this view <span>Select chart metrics & similarity priorities</span></summary><div className="desk-chips">{features.map(f=><label className="desk-check" key={f}><input type="checkbox" checked={lensMetrics.includes(f)} disabled={displayFeatures.length===1&&lensMetrics.includes(f)} onChange={()=>setLensMetrics(current=>current.includes(f)?current.filter(m=>m!==f):[...current,f])}/>{labels[f]}</label>)}</div><div className="desk-form-grid">{["Finishing","Creation","Involvement"].map(c=><label key={c}>{c} similarity priority<input type="number" min={0} max={200} value={(lensPriorities??priorities)[c]??100} onChange={e=>setLensPriorities({...lensPriorities??priorities,[c]:Math.max(0,Math.min(200,Number(e.target.value)))})}/></label>)}</div><button onClick={()=>{setLensMetrics(features);setLensPriorities(null);setNotice("Restored all chart metrics and dashboard similarity priorities.");}}>Reset view & priorities</button><p className="desk-footnote">Chart metric selection does not change the similarity feature set. Category priorities affect similarity, not search-target attainment. All-zero priorities withhold similarity scores.</p></details>
      <div className="desk-toolbar"><label>Add a comparison<select aria-label="Add comparison player" value={addKey} onChange={e=>setAddKey(e.target.value)}><option value="">Choose a player</option>{pool.filter(p=>!comparePlayers.some(c=>identity(c)===identity(p))).map(p=><option key={identity(p)} value={identity(p)}>{p.player_name}</option>)}</select></label><button disabled={!addKey||comparePlayers.length>=4} onClick={()=>{setComparisonKeys(current=>[...current,addKey].slice(0,3));setAddKey("");}}>+ Compare</button><label className="desk-check"><input type="checkbox" checked={reference} onChange={e=>setReference(e.target.checked)}/>Cohort-average reference</label><button onClick={exportComparison}>Download comparison card</button></div>
      <div className="desk-chips">{comparePlayers.map((p,i)=><span key={identity(p)} style={{borderColor:colors[i]}}>{p.player_name}{i>0&&<button aria-label={`Remove comparison ${p.player_name}`} onClick={()=>setComparisonKeys(current=>current.filter(k=>k!==identity(p)))}>×</button>}</span>)}</div>
      <p className="desk-footnote">Up to four players from {target.season} · {target.position} · {pool.length} profiles. Radar and reference use sample-adjusted percentiles; the recorded values below stay unchanged.</p>
      <div className="desk-comparison-grid"><div className="desk-chart"><ResponsiveContainer width="100%" height={400}><RadarChart data={radarData} outerRadius="68%"><PolarGrid stroke="#30443f"/><PolarAngleAxis dataKey="metric" tick={{fill:"#b4c2bd",fontSize:11}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/>{reference&&<Radar name="Cohort mean percentile" dataKey="average" stroke="#9aa7a3" fill="transparent" strokeDasharray="5 5" isAnimationActive={false}/ >}{comparePlayers.map((p,i)=><Radar key={identity(p)} name={p.player_name} dataKey={`p${i}`} stroke={colors[i]} fill={colors[i]} fillOpacity={.08} strokeWidth={2} isAnimationActive={false}/>) }<Tooltip/></RadarChart></ResponsiveContainer></div><div className="desk-distribution"><label>Distribution metric<select aria-label="Distribution metric" value={chartFeature} onChange={e=>setChartFeature(e.target.value)}>{features.map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><p>Recorded per-90 distribution · {distributionValues.length} observations</p><div className="desk-histogram" role="img" aria-label={`Ten-bin distribution of ${labels[chartFeature]} recorded per-90 values`}>{bins.map((bin,i)=><div key={i} title={`${bin.start.toFixed(2)}–${bin.end.toFixed(2)} /90: ${bin.count} players`}><b>{bin.count}</b><i style={{height:`${bin.count/Math.max(...bins.map(b=>b.count),1)*130}px`}}/><small>{bin.start.toFixed(1)}</small></div>)}</div>{comparePlayers.map((p,i)=><p key={identity(p)} style={{color:colors[i]}}>{p.player_name}: {valueText(observed(p,chartFeature),"per90")}</p>)}</div></div>
      <div className="desk-toolbar"><label>Table values<select aria-label="Comparison value basis" value={view} onChange={e=>setView(e.target.value as typeof view)}><option value="percentile">Adjusted percentiles</option><option value="per90">Recorded per 90</option></select></label></div><div className="desk-table-scroll"><table><thead><tr><th>Player</th>{features.map(f=><th key={f}>{labels[f]}</th>)}</tr></thead><tbody>{comparePlayers.map((p,i)=><tr key={identity(p)}><th style={{color:colors[i]}}>{p.player_name}</th>{features.map(f=><td key={f}>{(view==="percentile"?percentile(p,f,lookup):observed(p,f))?.toFixed(view==="percentile"?1:2)??"—"}</td>)}</tr>)}</tbody></table></div>
      <ScatterDiscovery pool={pool} features={features} x={xFeature} y={yFeature} onAxes={(x,y)=>{setXFeature(x);setYFeature(y);}} selected={comparePlayers.map(identity)} saved={savedKeys} onPreview={p=>setPreview({key:identity(p),context:"charts"})} onSave={addCandidate} onCompare={toggleChartPlayer}/>
    </>}
    {tab === "Projects" && <>
      <ReviewInbox projects={projects} players={players} features={features} datasetVersion={datasetVersion} onOpen={(projectId,key)=>{switchProject(projectId);setExpandedEntry(key);}} onAcknowledge={(projectId,key)=>{const player=players.find(p=>identity(p)===key);if(!player)return;setProjects(current=>current.map(project=>project.id===projectId?{...project,entries:project.entries.map(e=>e.key===key?{...e,profileSignature:profileSignature(player,features),reviewedDatasetVersion:datasetVersion}:e)}:project));setNotice("Record update acknowledged. Review dates, observations and missing-evidence tasks are unchanged.");}}/>
      <div className="flow-intro"><h3>Keep your best options together.</h3><p>{activeProject?`Working shortlist: ${activeProject.name}. Open a player to add notes or plan your next review.`:"Save a candidate from Review candidates to start a shortlist automatically, or create your own below."}</p></div>
      {activeProject&&<div className="desk-toolbar"><button onClick={()=>setDossierPlayers(activeProject.entries.map(e=>players.find(p=>identity(p)===e.key)).filter((p):p is ScoutPlayer=>Boolean(p)).slice(0,4))}>Preview project dossier</button><span>Charts cover the first four available candidates; all project notes and history are included.</span></div>}
      <div className="desk-toolbar"><label>Working shortlist<select aria-label="Active recruitment project" value={activeId} onChange={e=>switchProject(e.target.value)}><option value="">Unsaved brief</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
      <details className="flow-advanced" open={!activeProject}><summary>Manage shortlists <span>Create, import or switch your saved workspace</span></summary>
      <div className="desk-toolbar"><label>New project name<input aria-label="New project name" maxLength={120} placeholder="e.g. Creative winger options" value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><button onClick={()=>createProject()}>Create project</button><button disabled={!quickShortlist.length} onClick={()=>createProject(quickShortlist.map(entryFor))}>Copy quick shortlist</button><label className="desk-file-button">Import project<input type="file" accept="application/json,.json" aria-label="Import recruitment project" onChange={e=>{void importProject(e.target.files?.[0]);e.target.value="";}}/></label></div>
      </details>
      {!activeProject&&<p className="desk-empty">Create a named project to keep a brief, candidates and evidence together. Your existing quick shortlist stays untouched.</p>}
      {activeProject&&<><div className="desk-project-title"><h3>{activeProject.name}</h3><span>{activeProject.entries.length} candidates · source snapshot {activeProject.datasetVersion}</span></div><div className="desk-toolbar"><button onClick={()=>{try{const clean=validateProject({schemaVersion:1,project:activeProject});download(`scoutlab-project-${activeProject.id}.json`,JSON.stringify({schemaVersion:1,project:clean},null,2));}catch(error){setNotice(error instanceof Error?error.message:"Check project fields before exporting.");}}}>Export portable project</button><button onClick={()=>{const rows=activeProject.entries.map(e=>{const p=players.find(p=>identity(p)===e.key);return [p?.player_name??e.key,p?.club??"",p?.season??"",e.status,e.strengths,e.concerns,e.note,e.evidenceUrl];});download("scoutlab-project.csv",[["Player","Club","Season","Status","Strengths","Concerns","Notes","Evidence URL"],...rows].map(row=>row.map(quoteCsv).join(",")).join("\n"),"text/csv;charset=utf-8");}}>Export candidate CSV</button><button className="desk-danger" onClick={()=>{if(window.confirm(`Remove ${activeProject.name} from this browser? Export it first if you need a copy.`)){setProjects(current=>current.filter(p=>p.id!==activeId));setActiveId("");setNotice("Project removed from browser storage. Exported copies are unchanged.");}}}>Remove project</button></div><p className="desk-footnote">Project exports contain candidate references, brief settings and your notes—not the provider dataset. Import into another browser with a compatible dataset. Up to 20 projects, 64 candidates each. Notes save automatically; export a copy for backup.</p>{activeProject.datasetVersion!==datasetVersion&&<p className="desk-warning">This project was created against another dataset version. Recheck coverage and requirements before using the rankings.</p>}
      <div className="desk-project-entries">{activeProject.entries.map(e=>{const p=players.find(p=>identity(p)===e.key);return <article id={`review-${encodeURIComponent(e.key)}`} key={e.key}>
        <div className="desk-toolbar"><strong>{p?.player_name??"Profile unavailable in this dataset"}</strong><small>{p?`${p.club} · ${p.season}`:e.key}</small>{p&&<button onClick={()=>{setReportKey(e.key);setTab("Report");}}>Read report</button>}<button aria-label={`Remove project candidate ${p?.player_name??e.key}`} onClick={()=>{if(window.confirm("Remove this candidate and its notes from the project?"))setProjects(current=>current.map(project=>project.id===activeId?{...project,entries:project.entries.filter(entry=>entry.key!==e.key)}:project));}}>Remove</button></div>
        <div className="flow-entry-summary"><span>{e.status}</span><p>{e.nextAction||"No next action yet"}</p><small>{e.reviewDate?`Review: ${e.reviewDate}`:"No review date"}</small></div>
        <details className="flow-advanced flow-entry-details" open={expandedEntry===e.key?true:undefined}><summary>Notes & next steps <span>Strengths, concerns, review date & decision history</span></summary>
        {p&&<details className="flow-evidence"><summary>Sample & source details</summary><EvidencePanel compact player={p} features={features} generatedAt={generatedAt}/></details>}
        <div className="desk-entry-grid"><label>Review stage<select aria-label={`Review stage for ${p?.player_name??e.key}`} value={e.status} onChange={event=>updateEntry(e.key,{status:event.target.value as ProjectEntry["status"]})}>{["Longlist","Review","Priority","Passed"].map(s=><option key={s}>{s}</option>)}</select></label><label>Your observed strengths<textarea maxLength={5000} value={e.strengths} onChange={event=>updateEntry(e.key,{strengths:event.target.value})}/></label><label>Your concerns<textarea maxLength={5000} value={e.concerns} onChange={event=>updateEntry(e.key,{concerns:event.target.value})}/></label><label>Decision / follow-up notes<textarea maxLength={5000} value={e.note} onChange={event=>updateEntry(e.key,{note:event.target.value})}/></label><label>Evidence link<input type="url" maxLength={5000} placeholder="https://…" value={e.evidenceUrl} onChange={event=>updateEntry(e.key,{evidenceUrl:event.target.value})}/>{e.evidenceUrl&&(safeEvidenceUrl(e.evidenceUrl)?<a href={safeEvidenceUrl(e.evidenceUrl)!} target="_blank" rel="noreferrer">Open your evidence ↗</a>:<small className="desk-warning">Use a valid http/https link before exporting.</small>)}</label></div>
        <ObservationEditor entry={e} onUpdate={update=>updateEntry(e.key,update)} onNotice={setNotice}/>
        <ProjectReview entry={e} onUpdate={update=>updateEntry(e.key,update)} onNotice={setNotice}/>
        </details>
      </article>;})}</div></>}
    </>}
    {tab === "Checks" && diagnostics && <>
      <DatasetAudit players={players} features={features} datasetVersion={datasetVersion}/>
      <div className="desk-report-head"><span className="eyebrow">Model behaviour · not predictive validation</span><h3>How stable are this player's matches?</h3><p>{target.player_name} · {target.season} · {target.position} · {diagnostics.profiles} profiles · {diagnostics.incomplete} incomplete profiles</p></div>
      <p className="desk-footnote">These checks run locally on the active cohort and current category weights. Baseline: 900-minute prior. Top-{diagnostics.k} retention measures overlap, not rank order or transfer-success confidence. No model is retrained or changed.</p>
      <div className="desk-check-grid"><article><h4>Minutes-prior sensitivity</h4>{diagnostics.priors.map(r=><div className="desk-diagnostic" key={r.prior}><span>{r.prior} minutes</span><strong>{r.retained?.toFixed(0)??"—"}% retained</strong><small>Closest: {r.top}</small></div>)}</article><article><h4>Feature-removal sensitivity</h4>{diagnostics.ablations.map(r=><div className="desk-diagnostic" key={r.feature}><span>Without {labels[r.feature]}</span><strong>{r.retained?.toFixed(0)??"—"}% retained</strong><small>Closest: {r.top}</small></div>)}</article><article><h4>Candidate-pool sensitivity</h4>{diagnostics.cohorts.map(r=><div className="desk-diagnostic" key={r.minutes}><span>{r.minutes}+ minutes</span><strong>{r.retained?.toFixed(0)??"—"}% retained</strong><small>{r.size} eligible candidates · closest: {r.top}</small></div>)}<p>The selected reference is retained even if below the candidate cutoff. Cohort percentiles are recalculated for each scenario.</p></article><article><h4>Related metrics</h4>{diagnostics.correlations.length?<ul>{diagnostics.correlations.slice(0,6).map(r=><li key={r.left+r.right}>{labels[r.left]} / {labels[r.right]}: r={r.correlation.toFixed(2)} ({r.observations} profiles).</li>)}</ul>:<p>No feature pairs meet the |r| ≥ 0.80 screening threshold in this cohort.</p>}<p>Correlation flags possible redundant weighting. It does not prove that a metric should be removed.</p></article></div>
      <h4>Percentile-gap ranking vs standardized cosine baseline</h4><p className="desk-footnote">Cosine uses recorded per-90 values standardized within this cohort, without the minutes prior or category weights. It tests the legacy method family; it does not replay a previously fitted Python scaler. Zero-norm and incomplete vectors are excluded. Top-set overlap: {diagnostics.cosineAgreement.retained?.toFixed(0)??"—"}%.</p><div className="desk-table-scroll"><table><thead><tr><th>Rank</th><th>Current percentile-gap method</th><th>Similarity %</th><th>Standardized cosine baseline</th><th>Cosine (−1 to 1)</th></tr></thead><tbody>{Array.from({length:Math.max(diagnostics.baseline.length,diagnostics.cosine.length)},(_,i)=><tr key={i}><td>{i+1}</td><td>{diagnostics.baseline[i]?.name??"—"}</td><td>{diagnostics.baseline[i]?.score?.toFixed(1)??"—"}</td><td>{diagnostics.cosine[i]?.name??"—"}</td><td>{diagnostics.cosine[i]?.score?.toFixed(3)??"—"}</td></tr>)}</tbody></table></div>
    </>}
    </div>
    {dossierPlayers!==null&&<Dossier players={dossierPlayers} allPlayers={players} brief={brief} lookup={dossierLookup} features={features} project={activeProject} datasetVersion={datasetVersion} generatedAt={generatedAt} onClose={()=>setDossierPlayers(null)}/>}
  </section>;
}
