"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { CartesianGrid, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import { evidenceSummary, identity, labels, localDate, measuredSummary, observationCategories, observed, reviewReasons, safeEvidenceUrl, validateObservation } from "../lib/recruitment";
import type { MatchObservation, Percentiles, ProjectEntry, RecruitmentBrief, RecruitmentProject, ScoutPlayer } from "../lib/recruitment";
import { validateLens } from "../lib/lenses";
import type { AnalysisLens } from "../lib/lenses";

export function EvidenceSummary({player,features,lookup,brief,cohortSize,generatedAt}:{player:ScoutPlayer;features:string[];lookup:Percentiles;brief:RecruitmentBrief;cohortSize:number;generatedAt?:string}) {
  const summary=measuredSummary(player,features,lookup,brief),evidence=evidenceSummary(player,features,generatedAt);
  return <section className="scout-summary"><span className="eyebrow">Measured evidence · no AI inference</span><h4>At a glance</h4><p>{evidence.sample} · {summary.minutes?.toLocaleString()??"Unknown"} minutes · {cohortSize} {player.position.toLowerCase()} profiles in {player.season}.</p>
    <h5>What stands out</h5>{summary.findings.length?summary.findings.map(s=><details key={s.feature}><summary>{s.title}</summary><p>{s.evidence} Compared within this position and season, with a 900-minute prior. Source: {evidence.source}.</p></details>):<p>No supplied metric has a verified top-quarter rank in this cohort.</p>}
    <h5>Against your search</h5>{summary.gates.map(g=><p className="desk-warning" key={g}>{g}</p>)}{summary.gaps.length?summary.gaps.map(s=><details key={s.feature}><summary>{s.title}</summary><p>{s.evidence} {brief.name} · {brief.position} · {brief.season}. Recorded /90 is unadjusted; percentile ranks use sample adjustment.</p></details>):<p>{brief.rules.length?"All configured metric targets met.":"No metric targets configured."}</p>}
    <h5>Still needs checking</h5><p>Positioning, tracking runners, pressing and receiving under pressure need direct observation. They are not established by these attacking metrics.</p><p className="desk-footnote">{summary.missing.length?`Unavailable: ${summary.missing.map(f=>labels[f]).join(", ")}. `:""}{evidence.matchDate?`Last recorded match: ${evidence.matchDate}.`:"Latest performance match date is unverified."} {evidence.exportLabel}. Statistical output is not a tactical-fit grade.</p>
  </section>;
}

export function PlayerPreview({player,features,lookup,brief,cohortSize,generatedAt,saved,selected,comparisonCount,comparisonLimit,onClose,onSave,onCompare,onReport}:{player:ScoutPlayer;features:string[];lookup:Percentiles;brief:RecruitmentBrief;cohortSize:number;generatedAt?:string;saved:boolean;selected:boolean;comparisonCount:number;comparisonLimit:number;onClose:()=>void;onSave:()=>void;onCompare?:()=>void;onReport:()=>void}) {
  const root=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";close.current?.focus();const keyboard=(e:KeyboardEvent)=>{if(e.key==="Escape"){onClose();return;}if(e.key!=="Tab")return;const nodes=root.current?.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], summary, input, select, textarea');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};document.addEventListener("keydown",keyboard);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",keyboard);previous?.focus();};},[onClose]);
  return createPortal(<div className="scout-preview-backdrop" onClick={onClose}><div className="scout-preview" ref={root} role="dialog" aria-modal="true" aria-labelledby="preview-title" onClick={e=>e.stopPropagation()}><header><span className="eyebrow">Quick player preview</span><button ref={close} onClick={onClose}>Close preview ×</button></header><h3 id="preview-title">{player.player_name}</h3><p>{player.club} · {player.position} · {player.season}</p><div className="desk-toolbar"><button className="flow-primary" disabled={saved} onClick={onSave}>{saved?"✓ Shortlisted":"+ Shortlist"}</button>{onCompare&&<button aria-pressed={selected} disabled={!selected&&comparisonCount>=comparisonLimit} onClick={onCompare}>{selected?"Remove comparison":comparisonCount>=comparisonLimit?"Comparison full":"Add to comparison"}</button>}<button onClick={onReport}>Full report →</button></div><EvidenceSummary player={player} features={features} lookup={lookup} brief={brief} cohortSize={cohortSize} generatedAt={generatedAt}/><p className="desk-footnote">Close this preview to return to the same search, filters and position.</p></div></div>,document.body);
}

export function ObservationEditor({entry,onUpdate,onNotice}:{entry:ProjectEntry;onUpdate:(update:Partial<ProjectEntry>)=>void;onNotice:(message:string)=>void}) {
  const empty=():MatchObservation=>({id:crypto.randomUUID(),date:localDate(),opponent:"",role:"",category:"Positioning",outcome:"Observed",timestamp:"",note:"",evidenceUrl:""});
  const [draft,setDraft]=useState<MatchObservation|null>(null);
  const edit=(field:keyof MatchObservation,value:string)=>setDraft(d=>d?{...d,[field]:value}:d);
  return <section className="scout-observations"><h4>Match observations <small>Manual evidence, separate from statistics</small></h4><p className="desk-footnote">Record what you watched, including situations you could not assess. External links only; no footage is uploaded.</p>{(entry.observations??[]).map(o=><article key={o.id}><header><strong>{o.category} · {o.outcome}</strong><button onClick={()=>setDraft({...o})}>Edit observation</button><button onClick={()=>{if(window.confirm("Remove this match observation? Export your project first to keep a copy."))onUpdate({observations:entry.observations?.filter(item=>item.id!==o.id)});}}>Remove observation</button></header><p>{o.date} · vs {o.opponent} · {o.role}{o.timestamp?` · ${o.timestamp}`:""}</p><p className="scout-note">{o.note}</p>{safeEvidenceUrl(o.evidenceUrl)&&<a href={safeEvidenceUrl(o.evidenceUrl)!} target="_blank" rel="noreferrer">Open observation evidence ↗</a>}</article>)}
    {!draft?<button disabled={(entry.observations?.length??0)>=100} onClick={()=>setDraft(empty())}>+ Add match observation</button>:<form onSubmit={e=>{e.preventDefault();try{if((entry.observations?.length??0)>=100&&!entry.observations?.some(o=>o.id===draft.id))throw new Error("This candidate already has 100 observations.");const clean=validateObservation(draft);onUpdate({observations:entry.observations?.some(o=>o.id===clean.id)?entry.observations.map(o=>o.id===clean.id?clean:o):[...(entry.observations??[]),clean]});setDraft(null);onNotice("Match observation saved in this browser. Export your project to back it up.");}catch(error){onNotice(error instanceof Error?error.message:"Check your observation.");}}}><div className="desk-entry-grid"><label>Match date<input required type="date" value={draft.date} onChange={e=>edit("date",e.target.value)}/></label><label>Opponent<input required maxLength={200} value={draft.opponent} onChange={e=>edit("opponent",e.target.value)}/></label><label>Player's role<input required maxLength={200} placeholder="e.g. Right winger" value={draft.role} onChange={e=>edit("role",e.target.value)}/></label><label>Observation category<select aria-label="Observation category" value={draft.category} onChange={e=>edit("category",e.target.value)}>{observationCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Evidence status<select aria-label="Evidence status" value={draft.outcome} onChange={e=>edit("outcome",e.target.value)}><option>Observed</option><option>Not observed</option></select></label><label>Match / video timestamp<input maxLength={200} placeholder="e.g. 34:20" value={draft.timestamp} onChange={e=>edit("timestamp",e.target.value)}/></label><label>Observation note<textarea aria-label="Observation note" required maxLength={5000} placeholder="Describe the action and context; avoid conclusions you cannot support." value={draft.note} onChange={e=>edit("note",e.target.value)}/></label><label>Permitted evidence link (optional)<input type="url" maxLength={5000} value={draft.evidenceUrl} onChange={e=>edit("evidenceUrl",e.target.value)}/></label></div><div className="desk-toolbar"><button type="submit" className="flow-primary">Save observation</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
  </section>;
}

export function ReviewInbox({projects,players,features,datasetVersion,onOpen,onAcknowledge}:{projects:RecruitmentProject[];players:ScoutPlayer[];features:string[];datasetVersion:string;onOpen:(projectId:string,key:string)=>void;onAcknowledge:(projectId:string,key:string)=>void}) {
  const [filter,setFilter]=useState("All"),[limit,setLimit]=useState(6);
  const rows=projects.flatMap(project=>project.entries.map(entry=>{const player=players.find(p=>identity(p)===entry.key);return {project,entry,player,reasons:reviewReasons(entry,player,features,project.datasetVersion,datasetVersion)};})).filter(r=>r.reasons.length).sort((a,b)=>(a.entry.reviewDate||"9999").localeCompare(b.entry.reviewDate||"9999")||a.project.name.localeCompare(b.project.name));
  const shown=rows.filter(r=>filter==="All"||r.reasons.some(reason=>filter==="Due"?reason.includes("due"):filter==="Changed"?reason.includes("changed"):filter==="Missing"?reason.includes("missing")||reason.includes("unavailable"):reason.includes("observation")));
  return <section className="scout-inbox"><div className="desk-toolbar"><div><span className="eyebrow">Across your saved shortlists</span><h4>Scouting review inbox · {rows.length}</h4></div><label>Show review tasks<select aria-label="Review inbox filter" value={filter} onChange={e=>{setFilter(e.target.value);setLimit(6);}}>{["All","Due","Changed","Missing","Observations"].map(f=><option key={f}>{f}</option>)}</select></label></div><p className="desk-footnote">Local reminders only. Record changes compare saved signatures; older projects without signatures use dataset-version checks. No live monitoring or automatic name matching.</p>{shown.slice(0,limit).map(r=><article key={r.project.id+r.entry.key}><div><strong>{r.player?.player_name??"Player record unavailable"}</strong><small>{r.project.name}{r.entry.reviewDate?` · Review ${r.entry.reviewDate}`:""}</small><div className="desk-chips">{r.reasons.map(reason=><span key={reason}>{reason}</span>)}</div><p>{r.entry.nextAction||"Set a next action when you review this candidate."}</p></div><div className="desk-toolbar"><button onClick={()=>onOpen(r.project.id,r.entry.key)}>Open review →</button>{r.player&&r.reasons.some(reason=>reason.includes("changed"))&&<button onClick={()=>onAcknowledge(r.project.id,r.entry.key)}>Acknowledge record update</button>}</div></article>)}{!shown.length&&<p>No tasks in this view. Passed candidates are excluded.</p>}{shown.length>limit&&<button onClick={()=>setLimit(n=>n+6)}>Show 6 more reviews</button>}</section>;
}

export function LensManager({position,features,current,onApply,onNotice}:{position:string;features:string[];current:Omit<AnalysisLens,"id"|"name">;onApply:(lens:AnalysisLens)=>void;onNotice:(message:string)=>void}) {
  const [lenses,setLenses]=useState<AnalysisLens[]>([]),[ready,setReady]=useState(false),[name,setName]=useState("");
  const storage="scoutlab-analysis-lenses-v1";
  useEffect(()=>{try{const raw=localStorage.getItem(storage);if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||parsed.length>20)throw new Error("Invalid lens collection.");setLenses(parsed.map(l=>validateLens(l,features)));}setReady(true);}catch{onNotice("Saved lenses could not be restored. Existing storage was left untouched; use chart controls for this session.");}},[features,onNotice]);
  function save(next:AnalysisLens[]){try{localStorage.setItem(storage,JSON.stringify(next));setLenses(next);}catch{onNotice("Your lenses could not be saved. Browser storage may be full or disabled.");}}
  return <details className="flow-advanced"><summary>Saved analysis lenses <span>Metrics, chart settings & similarity priorities</span></summary><p className="desk-footnote">Lenses change the chart display and similarity category priorities, not the search requirements or underlying data. Separate saved lenses for each position. No tactical-grade model.</p><div className="desk-toolbar"><label>Lens name<input aria-label="Analysis lens name" maxLength={80} placeholder="e.g. Chance creation view" value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!ready||!name.trim()||lenses.length>=20} onClick={()=>{try{const lens=validateLens({...current,id:crypto.randomUUID(),name},features);save([...lenses,lens]);setName("");onNotice("Analysis lens saved in this browser.");}catch(error){onNotice(error instanceof Error?error.message:"Invalid lens.");}}}>Save current lens</button><label>Apply a saved lens<select aria-label="Apply analysis lens" value="" onChange={e=>{const lens=lenses.find(l=>l.id===e.target.value);if(lens)onApply(lens);}}><option value="">Choose a lens</option>{lenses.filter(l=>l.position===position).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div>{lenses.filter(l=>l.position===position).map(l=><div className="desk-toolbar" key={l.id}><span>{l.name} · {l.metrics.length} metrics</span><button onClick={()=>onApply(l)}>Apply</button><button onClick={()=>{if(window.confirm(`Remove saved lens ${l.name}?`))save(lenses.filter(item=>item.id!==l.id));}}>Remove lens</button></div>)}</details>;
}

export function ScatterDiscovery({pool,features,x,y,onAxes,selected,saved,onPreview,onSave,onCompare}:{pool:ScoutPlayer[];features:string[];x:string;y:string;onAxes:(x:string,y:string)=>void;selected:string[];saved:string[];onPreview:(p:ScoutPlayer)=>void;onSave:(p:ScoutPlayer)=>void;onCompare:(p:ScoutPlayer)=>void}) {
  const [sized,setSized]=useState(false),[query,setQuery]=useState(""),[limit,setLimit]=useState(8);
  const matches=(p:ScoutPlayer)=>`${p.player_name} ${p.club}`.toLowerCase().includes(query.trim().toLowerCase());
  const rows=pool.filter(p=>observed(p,x)!==null&&observed(p,y)!==null).map(p=>({key:identity(p),player:p,name:p.player_name,x:observed(p,x)!,y:observed(p,y)!,z:sized?(observed(p,"minutes")??0):1}));
  const median=(values:number[])=>{const v=values.slice().sort((a,b)=>a-b);return v.length?(v[Math.floor((v.length-1)/2)]+v[Math.ceil((v.length-1)/2)])/2:0;};
  const groups=[{name:"Cohort",color:"#536d63",test:(key:string)=>!selected.includes(key)&&!saved.includes(key)},{name:"Shortlisted",color:"#b8ff3d",test:(key:string)=>saved.includes(key)&&!selected.includes(key)},{name:"Comparison",color:"#ff2d8d",test:(key:string)=>selected.includes(key)}];
  const filtered=rows.filter(r=>matches(r.player)).sort((a,b)=>b.y-a.y||a.name.localeCompare(b.name));
  function clicked(value:unknown){const v=value as {key?:string;payload?:{key?:string}};const row=rows.find(r=>r.key===(v?.key??v?.payload?.key));if(row)onPreview(row.player);}
  return <section className="scout-discovery"><h4>Explore the player pool</h4><div className="desk-toolbar">{[{name:"Chance creation",x:"key_passes_p90",y:"xa_p90"},{name:"Finishing output",x:"xg_p90",y:"goals_p90"},{name:"Attack involvement",x:"xg_buildup_p90",y:"xg_chain_p90"}].filter(p=>features.includes(p.x)&&features.includes(p.y)).map(p=><button key={p.name} aria-pressed={x===p.x&&y===p.y} onClick={()=>onAxes(p.x,p.y)}>{p.name}</button>)}</div><div className="desk-toolbar"><label>Horizontal axis<select aria-label="Discovery horizontal axis" value={x} onChange={e=>onAxes(e.target.value,y)}>{features.map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><label>Vertical axis<select aria-label="Discovery vertical axis" value={y} onChange={e=>onAxes(x,e.target.value)}>{features.map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><label className="desk-check"><input type="checkbox" checked={sized} onChange={e=>setSized(e.target.checked)}/>Size dots by recorded minutes</label><label>Highlight / find a player<input type="search" aria-label="Find scatter player" value={query} onChange={e=>{setQuery(e.target.value);setLimit(8);}} placeholder="Name or club"/></label></div><p className="desk-footnote">Recorded /90 · {rows.length}/{pool.length} profiles have both metrics · median guides · click a dot to preview. Grey: cohort; lime: shortlisted; pink: comparison; cyan: search match.{sized?" Unknown minutes use the smallest dot; size is not a confidence interval.":""}</p>
    <div className="desk-chart"><ResponsiveContainer width="100%" height={350}><ScatterChart margin={{top:20,right:30,bottom:30,left:15}}><CartesianGrid stroke="#263b35" strokeDasharray="3 5"/><XAxis type="number" dataKey="x" name={labels[x]} tick={{fill:"#a1b2ab",fontSize:11}} label={{value:`${labels[x]} /90`,position:"bottom",fill:"#a1b2ab"}}/><YAxis type="number" dataKey="y" name={labels[y]} tick={{fill:"#a1b2ab",fontSize:11}}/><ZAxis type="number" dataKey="z" range={sized?[35,220]:[65,65]}/><Tooltip content={({active,payload})=>{const p=payload?.[0]?.payload;return active&&p?<div className="tooltip-card"><strong>{p.name}</strong><span>{labels[x]}: {p.x.toFixed(2)} /90</span><span>{labels[y]}: {p.y.toFixed(2)} /90</span><span>{p.player?.minutes??"Unknown"} minutes · click to preview</span></div>:null;}}/>{rows.length>0&&<><ReferenceLine x={median(rows.map(p=>p.x))} stroke="#526c61" strokeDasharray="5 5"/><ReferenceLine y={median(rows.map(p=>p.y))} stroke="#526c61" strokeDasharray="5 5"/></>}{((x==="xg_p90"&&y==="goals_p90")||(x==="goals_p90"&&y==="xg_p90")||(x==="xa_p90"&&y==="assists_p90")||(x==="assists_p90"&&y==="xa_p90"))&&rows.length>0&&<ReferenceLine segment={[{x:0,y:0},{x:Math.min(Math.max(...rows.map(r=>r.x)),Math.max(...rows.map(r=>r.y))),y:Math.min(Math.max(...rows.map(r=>r.x)),Math.max(...rows.map(r=>r.y)))}]} stroke="#ffcc3d" strokeDasharray="4 4"/>}{groups.map(g=><Scatter key={g.name} name={g.name} data={rows.filter(r=>g.test(r.key)&&!(query.trim()&&matches(r.player)))} fill={g.color} onClick={clicked} isAnimationActive={false}/>)}{query.trim()&&<Scatter name="Search match" data={filtered} fill="#27d8ff" onClick={clicked} isAnimationActive={false}/>}</ScatterChart></ResponsiveContainer></div>
    <details className="flow-advanced"><summary>Accessible player table <span>{filtered.length} matching profiles · ordered by vertical-axis value</span></summary><div className="desk-table-scroll"><table><thead><tr><th>Player</th><th>{labels[x]} /90</th><th>{labels[y]} /90</th><th>Minutes</th><th>Actions</th></tr></thead><tbody>{filtered.slice(0,limit).map(r=><tr key={r.key}><th>{r.name}<small>{r.player.club}</small></th><td>{r.x.toFixed(2)}</td><td>{r.y.toFixed(2)}</td><td>{observed(r.player,"minutes")?.toLocaleString()??"Unknown"}</td><td><div className="desk-toolbar"><button onClick={()=>onPreview(r.player)}>Preview</button><button disabled={saved.includes(r.key)} onClick={()=>onSave(r.player)}>{saved.includes(r.key)?"Shortlisted":"Shortlist"}</button><button aria-pressed={selected.includes(r.key)} onClick={()=>onCompare(r.player)}>{selected.includes(r.key)?"Remove comparison":"Compare"}</button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<p>No matching profiles with both metrics.</p>}{filtered.length>limit&&<button onClick={()=>setLimit(n=>n+8)}>Show 8 more players</button>}</details>
  </section>;
}
